export const search_focus = 'header/search_focus'
export const search_blur = 'header/search_blur'
export const set_list = 'header/set_list'
export const mouse_enter = 'header/mouse_enter'
export const mouse_leave = 'header/mouse_leave'
export const change_page = 'header/change_page'
